title: Chad Zirbel
author: Chad Zirbel
email: crzirbel@gmail.com
description: A wonderful site
twitter_username: crzirbel
github_username:  crzirbel

# Build settings
markdown: kramdown
theme: minima
