title: Chad Zirbel
author: Chad Zirbel
email: crzirbel@gmail.com
description: 
twitter_username: crzirbel
github_username:  crzirbel

# Build settings
markdown: kramdown
theme: minima

# plugins
plugins:
  - jekyll-seo-tag

# page order
header_pages:
  - Research.md
  - publications.md
  - CV.md
  - Contact.md
